### ISSUE TITLE
Activity streams for private data sets

### ISSUE THREAD

**Issue by cuboideum** [zarquon42b/ckan-anthro_theme#3]
Currently, activity streams are exclusively created for public datasets. As RDMBA is primarily used with private datasets, it would be helpful to activate the feature for this type as well.

Activation can be achieved by simply commenting out a line in a configuration file:

https://stackoverflow.com/questions/31063600/enable-ckan-activity-streams-for-private-datasets

**Comment by zarquon42b** [comment]
Done.
